/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FriendshipDTO
 */
export interface FriendshipDTO {
    /**
     * 
     * @type {number}
     * @memberof FriendshipDTO
     */
    id1: number;
    /**
     * 
     * @type {number}
     * @memberof FriendshipDTO
     */
    id2: number;
}

/**
 * Check if a given object implements the FriendshipDTO interface.
 */
export function instanceOfFriendshipDTO(value: object): value is FriendshipDTO {
    if (!('id1' in value) || value['id1'] === undefined) return false;
    if (!('id2' in value) || value['id2'] === undefined) return false;
    return true;
}

export function FriendshipDTOFromJSON(json: any): FriendshipDTO {
    return FriendshipDTOFromJSONTyped(json, false);
}

export function FriendshipDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FriendshipDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id1': json['id1'],
        'id2': json['id2'],
    };
}

export function FriendshipDTOToJSON(json: any): FriendshipDTO {
    return FriendshipDTOToJSONTyped(json, false);
}

export function FriendshipDTOToJSONTyped(value?: FriendshipDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id1': value['id1'],
        'id2': value['id2'],
    };
}

