/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupDTO
 */
export interface GroupDTO {
    /**
     * 
     * @type {string}
     * @memberof GroupDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GroupDTO
     */
    description: string;
}

/**
 * Check if a given object implements the GroupDTO interface.
 */
export function instanceOfGroupDTO(value: object): value is GroupDTO {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('description' in value) || value['description'] === undefined) return false;
    return true;
}

export function GroupDTOFromJSON(json: any): GroupDTO {
    return GroupDTOFromJSONTyped(json, false);
}

export function GroupDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'description': json['description'],
    };
}

export function GroupDTOToJSON(json: any): GroupDTO {
    return GroupDTOToJSONTyped(json, false);
}

export function GroupDTOToJSONTyped(value?: GroupDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'description': value['description'],
    };
}

