/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ProfileDTO,
} from '../models/index';
import {
    ProfileDTOFromJSON,
    ProfileDTOToJSON,
} from '../models/index';

export interface GetProfileByUserIDRequest {
    id: number;
}

/**
 * 
 */
export class ProfileControllerApi extends runtime.BaseAPI {

    /**
     */
    async getAllProfilesRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ProfileDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/profiles`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ProfileDTOFromJSON));
    }

    /**
     */
    async getAllProfiles(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ProfileDTO>> {
        const response = await this.getAllProfilesRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async getProfileByUserIDRaw(requestParameters: GetProfileByUserIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ProfileDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getProfileByUserID().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/users/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ProfileDTOFromJSON(jsonValue));
    }

    /**
     */
    async getProfileByUserID(requestParameters: GetProfileByUserIDRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ProfileDTO> {
        const response = await this.getProfileByUserIDRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
