// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FriendshipDTO
 */
export interface FriendshipDTO  {
    /**
     * 
     * @type {number}
     * @memberof FriendshipDTO
     */
    id1: number;
    /**
     * 
     * @type {number}
     * @memberof FriendshipDTO
     */
    id2: number;
}

export function FriendshipDTOFromJSON(json: any): FriendshipDTO {
    return {
        'id1': json['id1'],
        'id2': json['id2'],
    };
}

export function FriendshipDTOToJSON(value?: FriendshipDTO): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id1': value.id1,
        'id2': value.id2,
    };
}


