// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GroupDTO
 */
export interface GroupDTO  {
    /**
     * 
     * @type {string}
     * @memberof GroupDTO
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof GroupDTO
     */
    description: string;
}

export function GroupDTOFromJSON(json: any): GroupDTO {
    return {
        'name': json['name'],
        'description': json['description'],
    };
}

export function GroupDTOToJSON(value?: GroupDTO): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'name': value.name,
        'description': value.description,
    };
}


