// tslint:disable
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserDTO
 */
export interface UserDTO  {
    /**
     * 
     * @type {number}
     * @memberof UserDTO
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    username: string;
    /**
     * 
     * @type {string}
     * @memberof UserDTO
     */
    password: string;
}

export function UserDTOFromJSON(json: any): UserDTO {
    return {
        'id': json['id'],
        'username': json['username'],
        'password': json['password'],
    };
}

export function UserDTOToJSON(value?: UserDTO): any {
    if (value === undefined) {
        return undefined;
    }
    return {
        'id': value.id,
        'username': value.username,
        'password': value.password,
    };
}


